Основы JS. Примитивные типы данных. Первый пулреквест
js-tasks-ru/js-20220111_shevelyov-andreas pull request #2
Opened 2022-01-15 14:34 UTC by AndreiShev

Я не делал проверки на входящие параметры, полагая что в этих задачах добавлять их не было смысла. Если все таки стоит, то прошу пояснить.
Так же хотел бы спросить на каком языке стоило бы делать коммиты и отвечать на комментарии здесь, потому как ответ на нулевой пулреквест был на английском.

2022-01-15 14:35 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-01-17 16:50 UTC, dosandk commented
@AndreiShev на любом языке `ru` или `en` можно оставлять/отвечать на комментарии

2022-01-17 17:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-01-17 19:25 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    switch (param) {
👍 лайк за `switch...case` - это поможет явным образом обозначить какие параметры сортировки у нас существуют

2022-01-17 19:25 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +            result = sortArray(arr).reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-01-17 19:25 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    for(let i = 0; i < result.length; i++){
у массивов в JS, есть встроенный метод `sort`, попробуйте использовать именно его

2022-01-17 19:26 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let result = new Object();
проверьте, а точно ли тут `let`?
может `const`?

2022-01-17 19:26 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let result = new Object();
почему объявление объекта происходит через `new Object`, а не через `{}`?

2022-01-17 19:27 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    for (let key in obj) {
проверьте, а точно ли `key` это `let`?

2022-01-17 19:27 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +            console.log(key);
пожалуйста, не оставляйте отладочный консолей

2022-01-17 19:29 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    for (let key in obj) {
цикл `for...in` лучше использовать в связке с `obj.hasOwnProperty`, подробнее разберем на занятии

2022-01-17 19:29 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-01-17 20:07 UTC, AndreiShev commented on 02-javascript-data-types/2-pick/index.js
> +    let result = new Object();
хороший вопрос, скорее просто не доглядел и по привычке объявил таким образом

2022-01-17 20:51 UTC, AndreiShev commented on 02-javascript-data-types/2-pick/index.js
> +    let result = new Object();
В качестве значения переменной используется объект и перезапись переменной не планируется. То есть переменной не будет присвоен другой объект или значение другого типа.
В таком случае лучше будет использовать `const`

2022-01-17 21:34 UTC, AndreiShev commented on 02-javascript-data-types/3-omit/index.js
> +    for (let key in obj) {
В данном случае можно использовать `const`, потому как цикл отличается от того же `for`. А свойства объекта являются перечисляемыми

2022-01-17 21:38 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-01-18 14:48 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let result = new Object();
👍 good

2022-01-18 14:48 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    for (let key in obj) {
👍

2022-01-18 14:48 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +        if (!fields.includes(key) && obj.hasOwnProperty(key)) {
👍 good

2022-01-18 14:50 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +function compareFunction(a, b){
а почему бы не использовать только одну функцию, просто передавая аргументы в разном порядке:

```
case "asc":
            result = arrCopy.sort((a, b) => compareFunction(a, b));
case "desc":
            result = arrCopy.sort((a, b) => compareFunction(b, a));
```

2022-01-18 14:50 UTC, dosandk approved these changes
👍 good

2022-01-18 14:51 UTC, merged